/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __RDTSC_COUNT_BPF_SKEL_H__
#define __RDTSC_COUNT_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct rdtsc_count_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *bss;
	} maps;
	struct {
		struct bpf_program *handle_tp;
	} progs;
	struct {
		struct bpf_link *handle_tp;
	} links;
	struct rdtsc_count_bpf__bss {
		int my_pid;
	} *bss;

#ifdef __cplusplus
	static inline struct rdtsc_count_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct rdtsc_count_bpf *open_and_load();
	static inline int load(struct rdtsc_count_bpf *skel);
	static inline int attach(struct rdtsc_count_bpf *skel);
	static inline void detach(struct rdtsc_count_bpf *skel);
	static inline void destroy(struct rdtsc_count_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
rdtsc_count_bpf__destroy(struct rdtsc_count_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
rdtsc_count_bpf__create_skeleton(struct rdtsc_count_bpf *obj);

static inline struct rdtsc_count_bpf *
rdtsc_count_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct rdtsc_count_bpf *obj;
	int err;

	obj = (struct rdtsc_count_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = rdtsc_count_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	rdtsc_count_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct rdtsc_count_bpf *
rdtsc_count_bpf__open(void)
{
	return rdtsc_count_bpf__open_opts(NULL);
}

static inline int
rdtsc_count_bpf__load(struct rdtsc_count_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct rdtsc_count_bpf *
rdtsc_count_bpf__open_and_load(void)
{
	struct rdtsc_count_bpf *obj;
	int err;

	obj = rdtsc_count_bpf__open();
	if (!obj)
		return NULL;
	err = rdtsc_count_bpf__load(obj);
	if (err) {
		rdtsc_count_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
rdtsc_count_bpf__attach(struct rdtsc_count_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
rdtsc_count_bpf__detach(struct rdtsc_count_bpf *obj)
{
	return bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *rdtsc_count_bpf__elf_bytes(size_t *sz);

static inline int
rdtsc_count_bpf__create_skeleton(struct rdtsc_count_bpf *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "rdtsc_count_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	s->maps[0].name = "rdtsc_co.bss";
	s->maps[0].map = &obj->maps.bss;
	s->maps[0].mmaped = (void **)&obj->bss;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "handle_tp";
	s->progs[0].prog = &obj->progs.handle_tp;
	s->progs[0].link = &obj->links.handle_tp;

	s->data = (void *)rdtsc_count_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *rdtsc_count_bpf__elf_bytes(size_t *sz)
{
	*sz = 1672;
	return (const void *)"\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x88\x03\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0c\0\
\x01\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\x44\x75\x61\x6c\x20\x42\x53\x44\x2f\
\x47\x50\x4c\0\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\xc4\0\0\0\xc4\0\0\0\xc0\0\
\0\0\0\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\0\x01\0\0\x0d\x03\0\0\0\x01\0\0\0\x01\0\0\
\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\x09\0\0\0\x01\0\0\x0c\x02\0\0\0\
\x8b\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x05\0\0\0\
\x07\0\0\0\x0d\0\0\0\x90\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\xa4\0\0\0\0\0\0\
\x0e\x06\0\0\0\x01\0\0\0\xac\0\0\0\0\0\0\x0e\x03\0\0\0\x01\0\0\0\xb3\0\0\0\x01\
\0\0\x0f\0\0\0\0\x09\0\0\0\0\0\0\0\x04\0\0\0\xb8\0\0\0\x01\0\0\x0f\0\0\0\0\x08\
\0\0\0\0\0\0\0\x0d\0\0\0\0\x63\x74\x78\0\x69\x6e\x74\0\x68\x61\x6e\x64\x6c\x65\
\x5f\x74\x70\0\x6b\x70\x72\x6f\x62\x65\x2f\x70\x72\x6f\x63\x66\x73\x5f\x72\x77\
\x5f\x73\x68\x6f\x77\x2b\x30\x78\x32\x62\0\x2f\x68\x6f\x6d\x65\x2f\x77\x61\x6e\
\x67\x7a\x63\x2f\x44\x6f\x63\x75\x6d\x65\x6e\x74\x73\x2f\x46\x6c\x61\x6d\x65\
\x47\x72\x61\x70\x68\x2d\x66\x6f\x72\x2d\x6e\x65\x77\x2d\x64\x65\x66\x65\x6e\
\x73\x65\x2f\x65\x62\x70\x66\x2f\x70\x72\x6f\x6a\x65\x63\x74\x73\x2f\x72\x64\
\x74\x73\x63\x5f\x63\x6f\x75\x6e\x74\x2e\x62\x70\x66\x2e\x63\0\x09\x72\x65\x74\
\x75\x72\x6e\x20\x30\x3b\0\x63\x68\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\
\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x4c\x49\x43\x45\x4e\x53\x45\0\
\x6d\x79\x5f\x70\x69\x64\0\x2e\x62\x73\x73\0\x6c\x69\x63\x65\x6e\x73\x65\0\x9f\
\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\x1c\0\0\0\x30\0\0\0\0\0\0\0\
\x08\0\0\0\x13\0\0\0\x01\0\0\0\0\0\0\0\x04\0\0\0\x10\0\0\0\x13\0\0\0\x01\0\0\0\
\0\0\0\0\x2e\0\0\0\x80\0\0\0\x02\x50\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x19\0\0\
\0\x12\0\x03\0\0\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x74\0\0\0\x11\0\x04\0\0\0\0\0\
\0\0\0\0\x0d\0\0\0\0\0\0\0\x39\0\0\0\x11\0\x05\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\
\0\0\xbc\0\0\0\0\0\0\0\x04\0\0\0\x04\0\0\0\xd4\0\0\0\0\0\0\0\x04\0\0\0\x03\0\0\
\0\x2c\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\
\x0a\x0b\0\x2e\x74\x65\x78\x74\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\x2e\x65\x78\
\x74\0\x2e\x62\x73\x73\0\x68\x61\x6e\x64\x6c\x65\x5f\x74\x70\0\x2e\x6c\x6c\x76\
\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x6c\x69\x63\x65\x6e\x73\x65\0\x6d\x79\
\x5f\x70\x69\x64\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\
\x6b\x70\x72\x6f\x62\x65\x2f\x70\x72\x6f\x63\x66\x73\x5f\x72\x77\x5f\x73\x68\
\x6f\x77\x2b\x30\x78\x32\x62\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\x4c\x49\x43\
\x45\x4e\x53\x45\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\
\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x0a\x03\0\0\0\0\0\0\x7c\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\
\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x50\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x31\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x50\0\0\0\0\0\0\0\x0d\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x14\0\0\0\x08\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x60\0\0\0\0\0\0\
\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x6f\0\0\
\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x60\0\0\0\0\0\0\0\x9c\x01\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x6b\0\0\0\x09\0\0\0\x40\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc8\x02\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x0b\0\0\0\
\x06\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x0b\0\0\0\x01\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\xfc\x01\0\0\0\0\0\0\x50\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x07\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\xe8\x02\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x0b\0\0\0\x08\0\0\0\x08\0\0\0\0\0\
\0\0\x10\0\0\0\0\0\0\0\x23\0\0\0\x03\x4c\xff\x6f\0\0\0\x80\0\0\0\0\0\0\0\0\0\0\
\0\0\x08\x03\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x48\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x50\x02\0\0\
\0\0\0\0\x78\0\0\0\0\0\0\0\x01\0\0\0\x02\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\
\0\0";
}

#ifdef __cplusplus
struct rdtsc_count_bpf *rdtsc_count_bpf::open(const struct bpf_object_open_opts *opts) { return rdtsc_count_bpf__open_opts(opts); }
struct rdtsc_count_bpf *rdtsc_count_bpf::open_and_load() { return rdtsc_count_bpf__open_and_load(); }
int rdtsc_count_bpf::load(struct rdtsc_count_bpf *skel) { return rdtsc_count_bpf__load(skel); }
int rdtsc_count_bpf::attach(struct rdtsc_count_bpf *skel) { return rdtsc_count_bpf__attach(skel); }
void rdtsc_count_bpf::detach(struct rdtsc_count_bpf *skel) { rdtsc_count_bpf__detach(skel); }
void rdtsc_count_bpf::destroy(struct rdtsc_count_bpf *skel) { rdtsc_count_bpf__destroy(skel); }
const void *rdtsc_count_bpf::elf_bytes(size_t *sz) { return rdtsc_count_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
rdtsc_count_bpf__assert(struct rdtsc_count_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
	_Static_assert(sizeof(s->bss->my_pid) == 4, "unexpected size of 'my_pid'");
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __RDTSC_COUNT_BPF_SKEL_H__ */
